version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: yosoura
      POSTGRES_PASSWORD: yoyo123
      POSTGRES_DB: Members
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yosoura
      POSTGRES_PASSWORD: yoyo123
      POSTGRES_DB: Members
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
